site_name: thermal
site_url: https://sitmo.github.io/thermal
repo_url: https://github.com/sitmo/thermal
repo_name: sitmo/thermal
site_author: Thijs van den Berg
#copyright: Copyright &copy; 2022, Thijs van den Berg

#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
  - Contributing: contributing.md
  - Changelog: changelog.md

theme:
    name: readthedocs
    locale: en
    custom_dir: custom_theme/

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta

plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: yes
      watch:
        - thermal
